version: '3'
services:
  postgres:
    image: "postgres:11.8"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=masterpass
